import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowLeft, Check, ChevronDown } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { getAdminOrder, updateAdminOrderStatus, type AdminOrder, type AdminOrderStatus } from '../../../services/adminService'

const statuses: AdminOrderStatus[] = ['PENDING_PAYMENT', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED']
const money = (amount: number) => `₹${amount.toLocaleString('en-IN')}`
function OrderDetails() {
  const { orderId } = useParams(); const [order, setOrder] = useState<AdminOrder | null>(null); const [status, setStatus] = useState<AdminOrderStatus | ''>(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (orderId) getAdminOrder(orderId).then((result) => { setOrder(result); setStatus(result.orderStatus) }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : 'Could not load order.')) }, [orderId])
  if (!order) return <div className="admin-content"><div className="admin-state">{message || 'Loading order...'}</div></div>
  const saveStatus = async () => { if (!orderId || !status || status === order.orderStatus) return; if (!window.confirm(`Change this order to ${status.replace('_', ' ')}?`)) return; setSaving(true); setMessage(''); try { setOrder(await updateAdminOrderStatus(orderId, status)) } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update order.') } finally { setSaving(false) } }
  return <div className="admin-content"><Link className="admin-back-link" to="/admin/orders"><ArrowLeft size={16} /> All orders</Link><div className="admin-page-heading"><div><p className="admin-kicker">Order details</p><h2>{order.orderNumber}</h2><span className="admin-date">{new Date(order.createdAt).toLocaleString('en-IN')}</span></div><div className="admin-status-editor"><div className="admin-select-wrap"><select value={status} onChange={(event) => setStatus(event.target.value as AdminOrderStatus)}><option value="">Choose status</option>{statuses.map((value) => <option value={value} key={value}>{value.replace('_', ' ')}</option>)}</select><ChevronDown size={15} /></div><button className="admin-primary-button" type="button" onClick={saveStatus} disabled={saving || status === order.orderStatus}>{saving ? 'Saving...' : 'Update status'}</button></div></div>{message && <p className="admin-error">{message}</p>}<div className="admin-detail-grid"><InfoPanel title="Customer"><p><strong>{order.customer.name}</strong><br />{order.customer.email}<br />{order.customer.phone}</p></InfoPanel><InfoPanel title="Shipping address"><p>{order.address.fullName}<br />{order.address.addressLine1}<br />{order.address.addressLine2 && <>{order.address.addressLine2}<br /></>}{order.address.city}, {order.address.state} {order.address.pincode}<br />{order.address.phoneNumber}</p></InfoPanel><InfoPanel title="Payment"><p>Status <strong>{order.paymentStatus}</strong><br />Razorpay payment ID<br /><strong>{order.razorpayPaymentId || 'Not available'}</strong></p></InfoPanel></div><section className="admin-panel admin-order-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">Preparation</p><h3>Order items</h3></div></div>{order.items.map((item) => <div className="admin-item-detail" key={item.id}><div><h4>{item.productName}</h4><p>Qty {item.quantity} · {money(item.totalPrice)}</p></div>{item.isCustomizedScoop && <div className="scoop-config"><strong><Check size={14} /> Customized scoop · {item.numberOfScoops} scoops</strong><span>Colour: {item.colourTheme || 'No preference'} · Character: {item.preferredCharacter || 'No preference'}</span>
    <span>Age: {item.age ?? 'Not provided'}</span>
    <span>Preferred: {item.preferredItems.join(', ') || 'None'}</span><span>Exclude: {item.excludedItems.join(', ') || 'None'}</span>{item.additionalMessage && <span>Note: {item.additionalMessage}</span>}</div>}</div>)}<div className="admin-totals"><p>Subtotal <strong>{money(order.subtotal)}</strong></p><p>Shipping <strong>{money(order.shippingAmount)}</strong></p><p className="admin-grand-total">Total <strong>{money(order.totalAmount)}</strong></p></div></section></div>
}

function InfoPanel({ title, children }: { title: string; children: ReactNode }) { return <section className="admin-info-panel"><p className="admin-kicker">{title}</p>{children}</section> }
export default OrderDetails
